# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: 
    npm install -g @angular/cli
    npm install
    ng build --prod
  workingDirectory: 'angular/recruitment-application/'
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)/angular/recruitment-application/dist/recruitment-application/'
    Contents: 'index.html'
    TargetFolder: 'springboot/recruitment-application/src/main/resources/templates/'

- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)/dist/recruitment-application/'
    Contents: 'index.html'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.BuildDirectory)/dist/recruitment-application/'
    Contents: '**'
    TargetFolder: 'springboot/recruitment-application/src/main/resources/static/'